networks:
  default:
    driver: bridge

services:
  api:
    build:
      context: .
    networks:
      - default
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]
    ports:
      - "5001:5001"